# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[env._.nix-devshell]
enable = true
watch_files = ["flake.lock", "flake.nix", "devShell.nix", "treefmt.nix"]
