# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAH-mpwB7g3MnqYU-ooUBF1t99RP27dZ9addtMVXD";
    path = fetchzip {
      url = "https://www.sqlite.org/2025/sqlite-amalgamation-3490200.zip";
      hash = "sha256-zw9D86WTkqQlZIKcu2z808+4mc11bqct4GLnQsavDRw=";
    };
  }
  {
    name = "sqlite-3.48.0-F2R_axqHDgCxZnwMNgWsc8oFRjiZXj96WNJp9a4RlH0n";
    path = fetchgit {
      url = "https://github.com/vrischmann/zig-sqlite";
      rev = "ce4976f30ac25067e70f8791a6be7fe93175641f";
      hash = "sha256-vA24dPa6qxJ6rZUcLQy7hH6cHc3U2Epg83SQZ5J0XnA=";
    };
  }
]
