# SPDX-FileCopyrightText: 2024 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: build

permissions:
  packages: write

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_name == 'main'
      && github.ref
      || github.sha }}

jobs:
  devshell:
    uses: ./.github/workflows/devshell.yaml
    secrets: inherit
    with:
      cache_ver: 12

  build-containers:
    needs: devshell
    uses: ./.github/workflows/build-containers.yaml
    secrets: inherit
    with:
      cache_ver: 12
