# SPDX-FileCopyrightText: 2024 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: cleanup cache by branch

on:
  delete:

  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string

jobs:
  cleanup:
    if: ${{ github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: cleanup
        env:
          EVENT_BRANCH: ${{ github.event.ref }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BRANCH: ${{ inputs.branch }}
          REPO: ${{ github.repository }}
        run: |
          case ${GITHUB_EVENT_NAME:?} in
          delete) branch=${EVENT_BRANCH:?} ;;
          workflow_dispatch) branch=${INPUT_BRANCH:?} ;;
          esac

          : "${REPO:?} ${branch:?}"

          gh extension install actions/gh-actions-cache

          set +e

          done=0
          while ((done != 1)); do
            keys=($(gh actions-cache list \
              -R "$REPO" \
              -B "$branch" \
              -L 100 \
              --order desc \
              --sort size \
              | cut -f1))

            if ((${#keys[@]} < 1)); then
              done=1
              break
            fi

            for key in "${keys[@]}"; do
              gh actions-cache delete "$key" -R "$REPO" -B "$BRANCH" --confirm
            done
          done
