# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: check

on:
  workflow_call:
    inputs:
      check:
        required: true
        type: string

      pushFilter:
        required: true
        type: string

    secrets:
      CACHIX_SIGNING_KEY:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: ${{ github.repository_owner }}
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          pushFilter: ${{ inputs.pushFilter }}

      - name: build
        env:
          CHECK: ${{ inputs.check }}
        run: |-
          system=$(nix config show system)
          nix -L build --keep-going ".#checks.${system:?}.${CHECK:?}"
