# SPDX-FileCopyrightText: 2024 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: devshell

on:
  workflow_call:
    inputs:
      cache_ver:
        default: 1
        type: number
      nix_public_key:
        default: ${{ vars.nix_public_key }}
        type: string
    secrets:
      nix_secret_key:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-nix
        id: setup-nix
        with:
          always_setup: false
          cache_ver: ${{ inputs.cache_ver }}
          name: devshell
          nix_public_key: ${{ inputs.nix_public_key }}
          nix_secret_key: ${{ secrets.nix_secret_key }}

      - name: cache devshell
        if: steps.setup-nix.outputs.cache-hit != 'true'
        run: |
          nix=$(command -v nix)
          system=$(nix eval --impure --raw --expr 'builtins.currentSystem')
          sudo "${nix:?}" copy --to "$CACHE_URL" ".#devShells.${system:?}.github"
          sudo "${nix:?}" flake archive --to "$CACHE_URL" .
